apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        default: cbp-qa-automation+fmautomation@beescloud.com
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
          echo "${{ inputs.username }}"
         
          echo "${{ inputs.username =~ 'fmautomation@beescloud.com' }}"
          echo ${{ inputs.username =~ 'fmautomation@beescloud.com' }}
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh

      - name: without quotes
        if: ${{ inputs.username =~ 'fmautomation' }}
        run: |
          echo "hello world"          
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh

      - name: With quotes
        if: "${{ inputs.username =~ 'fmautomation' }}"
        run: |
          echo "hello world"
          echo "${{ inputs.username }}"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh

      
